[package]
name = "advent-of-code-2019"
version = "0.1.0"
authors = ["Chris W Jones <chris@christopherjones.us>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.8"
log = "0.4"
env_logger = "0.7.1"
